name: 1.0$(Rev:.r)

pr: none
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - Backend/AnimalRescue/*
    exclude:
    - Frontend/*

resources:
  - repo: self

pool:
  vmImage: ubuntu-20.04

variables:
  imageRepository: 'pet-sos/animalrescue/api'
  containerRegistry: 'ghcr.io'
  dockerRegistryServiceConnection: 'AnimalRescue-GitHub-packages'
  imagePullSecret: 'github'
  kubernetesServiceConnection: 'animalrescue-aks'
  baseServiceName: 'animalrescue-api'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: 'Backend/AnimalRescue/Dockerfile'
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(Build.BuildNumber)
          - upload: Backend/AnimalRescue/deployment/manifests
            artifact: manifests

  - stage: DEV
    displayName: DEV
    dependsOn: Build
    variables:
      - group: 'animalrescue-dev'
    jobs:
      - template: deploy.yml
        parameters:
          environment: "DEV"

  - stage: PROD
    displayName: PROD
    dependsOn: DEV
    variables:
      - group: 'animalrescue-prod'
    jobs:
      - template: deploy.yml
        parameters:
          environment: "PROD"
